// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrR_gjuQ2ZbXv1kSAZV0QbqUvfC4vScZk',
    appId: '1:441036325327:web:777ea07121a12bdd6c52ba',
    messagingSenderId: '441036325327',
    projectId: 'washandgo-a2578',
    authDomain: 'washandgo-a2578.firebaseapp.com',
    storageBucket: 'washandgo-a2578.appspot.com',
    measurementId: 'G-YP807KHJFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFiReIaMD9D7hNmsbZPzJfkFsMiUxA1PA',
    appId: '1:441036325327:android:55bdcbf6104275e26c52ba',
    messagingSenderId: '441036325327',
    projectId: 'washandgo-a2578',
    storageBucket: 'washandgo-a2578.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6IiauytdT8MbmBMoAzJ_KmOMXgkpKq_s',
    appId: '1:441036325327:ios:901a42db38c3c62d6c52ba',
    messagingSenderId: '441036325327',
    projectId: 'washandgo-a2578',
    storageBucket: 'washandgo-a2578.appspot.com',
    iosBundleId: 'com.example.washAndGo',
  );
}
